name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          # Don't return a nonzero exit code on errors
          vale_flags: "--no-exit"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}